name: Food POS's Storybook Productiton Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.FOOD_POS_STORYBOOK_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.FOOD_POS_STORYBOOK_PROJECT_ID }}
on:
  pull_request:
    branches:
      - main
jobs:
  Deploy-Storybook-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build Storybook
        run: |
          pnpm build-storybook

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.FOOD_POS_STORYBOOK_VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: |
          vercel build --token=${{ secrets.FOOD_POS_STORYBOOK_VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          vercel deploy --prebuilt --token=${{ secrets.FOOD_POS_STORYBOOK_VERCEL_TOKEN }}
